_BASE_: "Base-RCNN-VoVNet-FPN.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/q98pypf96rhtd8y/vovnet39_ese_detectron2.pth?dl=1"
  MASK_ON: True
  VOVNET:
    CONV_BODY : "V-39-eSE"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/MRCN-V2-39-3x"